subroutine z_hc_sub (rho_in)
    ! subroutine for the compresibility factor contribution from hard chain HC term calculation
    ! the HC incorporates the hard sphere HS contribution according to the paper Gross-Sadowski 2001
    ! - preapre the necesarry components such as dzeta_fun, rdf_sub and z_hs_sub
    !	* calling only when necesarry
    ! - the actual initialization
    ! - computation of the hard chain compresibility contribution
    !	* also second derivative if required
    ! - parameter update in control module
    !
    !	== LAST MODIFICATIONS ==
    !	15.5.2017 - D.C - descriptions and comments
    !	20.6.2017 - D.C - init_flag_g dependency omitment(partial) -> moved to parent control module -> replaced by single flag
    !	04.7.2017 - D.C - moving the z_hs contribution to get method in control mod

    use control_mod, only : dp, n_comp, sec_der, &
            &    stdout, stderr, stddeb, stdlog, &
            &   a_hs, a_hs_dx, a_hs_dtt, &
            &   g_ij, g_ij_drho, g_ij_drho2, g_ij_drho3, &
            &   z_hc, z_hc_drho, z_hc_drho2, &
            &   init_flag_gij, init_flag_zhc
    use contrib_mod, only : mol_rat

    use param_list_mod, only : param_m
    implicit none
    ! variable section IN/OUT
    real(dp), intent(in) :: rho_in ! the input density
    ! local variables outputed into control_mod
    real(dp) :: z_hc_       ! the hard chain compressibility contribution
    real(dp) :: z_hc_drho_  ! the first density derivative of hard chain compressibility contribution
    real(dp) :: z_hc_drho2_ ! the second density derivative of hard chain compressibility contribution
    ! local variables
    integer :: i ! counter

    !------- PREPARING ------
    write (stddeb,*) "==> z_hc_sub" !DEBUG

    ! call for the required level 1 subroutine rdf
    if (init_flag_gij .eqv. .false.) then
        call rdf_sub(rho_in)
    end if

    ! based upon paper Gross-Sadowski 2001 application of PC-SAFT eq (A.25)
    !	-solved because the z_hs has own computation procedure
    write (stddeb,*) '-----  HC  -----'  ! DEBUG just for brevity of debug

    z_hc_ = 0.0_dp
    z_hc_drho_ = 0.0_dp
    z_hc_drho2_ = 0.0_dp

    do i = 1, n_comp
        z_hc_ = z_hc_ &
                & + mol_rat(i) * (1.0_dp - param_m(i)) * rho_in * g_ij_drho(i, i) / g_ij(i, i)
        z_hc_drho_ = z_hc_drho_ &
                & + mol_rat(i) * (1.0_dp - param_m(i)) * (-rho_in * (g_ij_drho(i, i) / g_ij(i, i))**2  &
                        & + g_ij_drho(i, i) / g_ij(i, i) &
                        & + rho_in * g_ij_drho2(i, i) / g_ij(i, i))! computed and simplified by maple
        if (sec_der .eqv. .true.) then
            z_hc_drho2_ = z_hc_drho2_ &
                    & + mol_rat(i) * (1.0_dp - param_m(i)) &
                            & * (2.0_dp * rho_in * (g_ij_drho(i, i) / g_ij(i, i))**3 &
                                    & - 3.0_dp * g_ij_drho(i, i) * g_ij_drho2(i, i) * rho_in / g_ij(i, i)**2 &
                                    & + g_ij_drho3(i, i) * rho_in / g_ij(i, i) &
                                    & - 2.0_dp * (g_ij_drho(i, i) / g_ij(i, i))**2 &
                                    & + 2.0_dp * g_ij_drho2(i, i) / g_ij(i, i)) ! computed, simplified and generated by maple
            ! OLD presently unused
            ! 			z_hc_drho3_ = z_hc_drho3_ &
            ! 					&	  + mol_rat(i)*( 1.0_dp-param_m(i)) &
            ! 					    &  *(-6.0_dp*rho_in*( g_ij_drho(i,i)/g_ij(i,i) )**4 &
            ! 					    &    + ( 12.0_dp*rho_in*g_ij_drho2(i,i)*g_ij_drho(i,i)**2 &
            ! 					    &        +6.0_dp*g_ij_drho(i,i)**3 )/g_ij(i,i)**3 &
            ! 					    &    + ( -3.0_dp*rho_in*g_ij_drho2(i,i)**2 &
            ! 					    &        -4.0_dp*rho_in*g_ij_drho(i,i)*g_ij_drho3(i,i) &
            ! 					    &        -9.0_dp*g_ij_drho(i,i)*g_ij_drho2(i,i) )/g_ij(i,i)**2 &
            ! 					    &    + (  3.0_dp*g_ij_drho3(i,i) &
            ! 					    &        + rho_in*g_ij_drho4(i,i) )/g_ij(i,i) )
            !
            ! 			z_hc_drho4_ = z_hc_drho4_ &
            ! 					&	  + mol_rat(i)*( 1.0_dp-param_m(i)) &
            ! 						&  *( 24.0_dp*rho_in*(g_ij_drho(i,i)/g_ij(i,i))**5 &
            ! 						&   + ( -60.0_dp*rho_in*g_ij_drho2(i,i)*g_ij_drho(i,i)**3 &
            ! 						&       -24.0_dp*g_ij_drho(i,i)**4 )/g_ij(i,i)**4 &
            ! 						&   + (  30.0_dp*rho_in*g_ij_drho(i,i)*g_ij_drho2(i,i)**2 &
            ! 						&       +20.0_dp*rho_in*g_ij_drho3(i,i)*g_ij_drho(i,i)**3 &
            ! 						&       +48.0_dp*g_ij_drho2(i,i)*g_ij_drho(i,i)**2 )/g_ij(i,i)**3 &
            ! 						&   + ( -10.0_dp*rho_in*g_ij_drho2(i,i)*g_ij_drho3(i,i) &
            ! 						&        -5.0_dp*rho_in*g_ij_drho(i,i)*g_ij_drho4(i,i) &
            ! 						&       -12.0_dp*g_ij_drho2(i,i)**2 &
            ! 						&       -16.0_dp*g_ij_drho(i,i)*g_ij_drho3(i,i) )/g_ij(i,i)**2 &
            ! 						&   + (  rho_in*g_ij_drho5(i,i) &
            ! 						&        +4.0_dp*g_ij_drho4(i,i) )/g_ij(i,i) )
        end if
    end do

    write (stddeb,*) "z_hc_      : ",z_hc_ ! DC DEBUG
    write (stddeb,*) "z_hc_drho_ : ",z_hc_drho_ ! DC DEBUG
    if (sec_der .eqv. .true.) then
        write (stddeb,*) "z_hc_drho2_: ",z_hc_drho2_ ! DC DEBUG
    end if
    write (stddeb,*) '----- ++++ -----'  ! DEBUG just for brevity of debug

    z_hc = z_hc_
    z_hc_drho = z_hc_drho_
    if (sec_der .eqv. .true.) then
        z_hc_drho2 = z_hc_drho2_
    end if

    init_flag_zhc = .true.
    write (stddeb,*) "<== z_hc_sub" !DEBUG
end subroutine z_hc_sub
